version: 2

models:
  - name: mart_tt_commented_videos
    description: |
      Highest-comment Videos: Identifies the Top 10 trending videos with the highest comment counts per country.  
      - Uses `int_unique_video` as the source.  
      - Ranks videos by comment_count within each country.  
      - Keeps only the Top 10 per country.  
      - Final output contains video details such as title, channel, category, and published date.  

    columns:
      - name: title
        description: Title of the trending video.
        tests:
          - not_null

      - name: published_at
        description: Timestamp when the video was published on YouTube.
        tests:
          - not_null

      - name: channel_title
        description: Channel name that published the video.
        tests:
          - not_null

      - name: category_id
        description: Category identifier representing the type of content.
        tests:
          - not_null

      - name: comment_count
        description: Number of comments on the video.
        tests:
          - not_null

  - name: mart_tt_liked_videos
    description: |
      Highest-like Videos: Identifies the Top 10 trending videos with the highest like counts per country.  
      - Uses `int_unique_video` as the source.  
      - Ranks videos by like_count within each country.  
      - Keeps only the Top 10 per country.  
      - Final output contains video details such as title, channel, category, and published date.  

    columns:
      - name: title
        description: Title of the trending video.
        tests:
          - not_null

      - name: published_at
        description: Timestamp when the video was published on YouTube.
        tests:
          - not_null

      - name: channel_title
        description: Channel name that published the video.
        tests:
          - not_null

      - name: category_id
        description: Category identifier representing the type of content.
        tests:
          - not_null

      - name: like_count
        description: Number of likes on the video.
        tests:
          - not_null

  - name: mart_tt_popular_tags
    description: |
      Popular Tags: Identifies the Top 100 most frequently used tags per country 
      for each load snapshot.  
      - Explodes comma-separated tags from `int_youtube_tag`.  
      - Counts frequency of tags per country and load timestamp.  
      - Ranks tags and filters top 100 per country.  
      - Useful for analyzing trending topics, cultural differences, and shifts 
        in tag popularity over time.  

    columns:
      - name: country
        description: Country code representing the source of the trending videos.
        tests:
          - not_null

      - name: tag
        description: Individual YouTube tag extracted from trending videos.
        tests:
          - not_null

      - name: tag_count
        description: Number of times the tag appeared in trending videos for a given country.
        tests:
          - not_null

      - name: total_tags
        description: Total number of tag occurrences in the country for the given load snapshot.
        tests:
          - not_null

      - name: load_ts
        description: Load timestamp indicating the batch/snapshot of data ingestion.
        tests:
          - not_null

version: 2

models:
  - name: mart_tt_viewed_videos
    description: |
      Highest-Viewed Videos: Identifies the Top 10 trending videos (by view_count) 
      for each country.  
      Steps performed:
        1. Rank videos within each country by `view_count`.  
        2. Filter to keep only the Top 10 per country.  
        3. Select video details for final output.  
      Use case: Useful for analyzing audience preferences, most popular videos per region, 
      and tracking which videos achieve the widest reach.

    columns:
      - name: title
        description: Title of the YouTube video.
        tests:
          - not_null

      - name: published_at
        description: Timestamp when the video was originally published on YouTube.
        tests:
          - not_null

      - name: channel_title
        description: Channel name of the video creator.
        tests:
          - not_null

      - name: category_id
        description: Numeric identifier representing the videos content category.
        tests:
          - not_null

      - name: view_count
        description: Total number of views recorded for the video.
        tests:
          - not_null

  - name: mart_tt_like_view_percentage
    description: |
      Highest Like-to-View %: Identifies the Top 10 trending videos with the highest 
      engagement rate, measured as the percentage of likes relative to views.  
      Steps performed:
        1. Filter out videos with null or zero `like_count`.  
        2. Retain the record with the highest `view_count` per video (rn = 1).  
        3. Calculate `like_view_percentage = (like_count / view_count) * 100`.  
        4. Rank and keep Top 10 videos with the highest engagement.  
      Use case: Highlights videos that achieve unusually high audience approval, 
      even if absolute views are lower.

    columns:
      - name: title
        description: Title of the YouTube video.
        tests:
          - not_null

      - name: channel_title
        description: Channel name of the video creator.
        tests:
          - not_null

      - name: published_at
        description: Timestamp when the video was originally published on YouTube.
        tests:
          - not_null

      - name: category_id
        description: Numeric identifier representing the videos content category.
        tests:
          - not_null

      - name: view_count
        description: Total number of views recorded for the video.
        tests:
          - not_null

      - name: like_count
        description: Total number of likes recorded for the video.
        tests:
          - not_null

      - name: like_view_percentage
        description: Engagement rate calculated as `(like_count / view_count) * 100`, rounded to 2 decimals.
        tests:
          - not_null

  - name: mart_tt_comment_view_percentage
    description: |
      Highest Comment-to-View %: Identifies the Top 10 trending videos with the highest 
      engagement rate, measured as the percentage of comments relative to views.  
      Steps performed:
        1. Filter out videos with null or zero `comment_count`.  
        2. Retain the record with the highest `view_count` per video (rn = 1).  
        3. Calculate `comment_view_percentage = (comment_count / view_count) * 100`.  
        4. Rank and keep Top 10 videos with the highest comment engagement.  
      Use case: Highlights videos that spark high audience discussion and interaction.

    columns:
      - name: title
        description: Title of the YouTube video.
        tests:
          - not_null

      - name: channel_title
        description: Channel name of the video creator.
        tests:
          - not_null

      - name: published_at
        description: Timestamp when the video was originally published on YouTube.
        tests:
          - not_null

      - name: category_id
        description: Numeric identifier representing the videos content category.
        tests:
          - not_null

      - name: view_count
        description: Total number of views recorded for the video.
        tests:
          - not_null

      - name: comment_count
        description: Total number of comments recorded for the video.
        tests:
          - not_null

      - name: comment_view_percentage
        description: Engagement rate calculated as `(comment_count / view_count) * 100`, rounded to 2 decimals.
        tests:
          - not_null

  - name: mart_tt_comment_like_percentage
    description: |
      Highest Comment-to-Like %: Identifies the Top 10 trending videos with the highest 
      engagement rate, measured as the percentage of comments relative to likes.  
      Steps performed:
        1. Filter out videos with null or zero `comment_count`.  
        2. Retain records where likes exist for comparison.  
        3. Calculate `comment_like_percentage = (comment_count / like_count) * 100`.  
        4. Rank and keep Top 10 videos with the highest comment-to-like ratio.  
      Use case: Highlights videos that spark discussion relative to the number of likes they receive.

    columns:
      - name: title
        description: Title of the YouTube video.
        tests:
          - not_null

      - name: channel_title
        description: Channel name of the video creator.
        tests:
          - not_null

      - name: published_at
        description: Timestamp when the video was originally published on YouTube.
        tests:
          - not_null

      - name: category_id
        description: Numeric identifier representing the videos content category.
        tests:
          - not_null

      - name: like_count
        description: Total number of likes recorded for the video.
        tests:
          - not_null

      - name: comment_count
        description: Total number of comments recorded for the video.
        tests:
          - not_null

      - name: comment_like_percentage
        description: Engagement rate calculated as `(comment_count / like_count) * 100`, rounded to 2 decimals.
        tests:
          - not_null

  - name: mart_tt_watch_countries
    description: |
      Top Watching Countries: Identifies the Top 10 countries that watch the most trending videos.  
      This mart aggregates YouTube trending data at the country level and provides:  
        1. `unique_trending_videos` → number of distinct trending videos per country.  
        2. `total_views` → total views accumulated by all trending videos in that country.  
        3. `view_rank` → rank of countries by total views (1 = highest).  
        4. `video_rank` → rank of countries by number of unique trending videos (1 = highest).  
      The result helps highlight which countries contribute most to trending video popularity.  

    columns:
      - name: country
        description: Country code where the video was trending.
        tests:
          - not_null

      - name: unique_trending_videos
        description: Number of distinct videos that trended in this country.
        tests:
          - not_null

      - name: total_views
        description: Total number of views across all trending videos in this country.
        tests:
          - not_null

      - name: view_rank
        description: Rank of the country based on total views (1 = highest total views).
        tests:
          - not_null

      - name: video_rank
        description: Rank of the country based on number of unique trending videos (1 = highest).
        tests:
          - not_null

  - name: mart_tt_trending_videos
    description: |
      Most Globally Trending Videos: Identifies the Top 10 videos that trended across the highest number of countries.  
      This mart performs the following steps:  
        1. Counts in how many countries each video has appeared in the trending list.  
        2. Ranks each video by view_count (keeping the record with the highest views).  
        3. Joins metadata with the top 500 most globally trended videos.  
      The output provides one row per video enriched with title, channel, category, views, and country reach.  

    columns:
      - name: title
        description: Title of the trending YouTube video.
        tests:
          - not_null

      - name: published_at
        description: Timestamp when the video was published on YouTube.
        tests:
          - not_null

      - name: channel_title
        description: Name of the YouTube channel that published the video.
        tests:
          - not_null

      - name: category_id
        description: YouTube category ID associated with the video.
        tests:
          - not_null

      - name: view_count
        description: Total number of views for the video (highest recorded across countries).
        tests:
          - not_null

      - name: country_count
        description: Number of unique countries in which this video trended (reach metric).
        tests:
          - not_null
          - value_between:
              min_value: 1
              max_value: 150